/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.auvua.visionservice;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FilterType implements org.apache.thrift.TEnum {
  RGB_THRESHOLD(0),
  HSV_THRESHOLD(1),
  GAUSSIAN_BLUR(2),
  CANNY_EDGE(3),
  HOUGH_LINE(4),
  HOUGH_CIRCLE(5),
  SCALE(6);

  private final int value;

  private FilterType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FilterType findByValue(int value) { 
    switch (value) {
      case 0:
        return RGB_THRESHOLD;
      case 1:
        return HSV_THRESHOLD;
      case 2:
        return GAUSSIAN_BLUR;
      case 3:
        return CANNY_EDGE;
      case 4:
        return HOUGH_LINE;
      case 5:
        return HOUGH_CIRCLE;
      case 6:
        return SCALE;
      default:
        return null;
    }
  }
}
