#
# Autogenerated by Thrift Compiler (0.9.3)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#
#  options string: py
#

from thrift.Thrift import TType, TMessageType, TException, TApplicationException

from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol, TProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Level:
  """
  Enumerations
  """
  INFO = 0
  WARNING = 1
  SEVERE = 2

  _VALUES_TO_NAMES = {
    0: "INFO",
    1: "WARNING",
    2: "SEVERE",
  }

  _NAMES_TO_VALUES = {
    "INFO": 0,
    "WARNING": 1,
    "SEVERE": 2,
  }

